#ifndef _ALTERA_HDMI_DMAC_0_H_
#define _ALTERA_HDMI_DMAC_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'system_bd' in
 * file '../../soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hdmi_dmac_0' and devices
 * connected to the following master:
 *   m_src_axi
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'sys_hps_bridges', class 'hps_bridge_avalon'
 * The macros are prefixed with 'SYS_HPS_BRIDGES_'.
 * The prefix is the slave descriptor.
 */
#define SYS_HPS_BRIDGES_COMPONENT_TYPE hps_bridge_avalon
#define SYS_HPS_BRIDGES_COMPONENT_NAME sys_hps_bridges
#define SYS_HPS_BRIDGES_BASE 0x0
#define SYS_HPS_BRIDGES_SPAN 0x0
#define SYS_HPS_BRIDGES_END 0xffffffff


#endif /* _ALTERA_HDMI_DMAC_0_H_ */
